package com.mycompany.aiderezo;


import com.mycompany.aiderezo.Sousreseau;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author t.real
 */
public class Saisie extends javax.swing.JFrame {

    /**
     * Creates new form Saisie
     */
    public Saisie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdresseIp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aide Rezo");

        AdresseIp.setToolTipText("Saisir l'adresse ip: ");
        AdresseIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdresseIpActionPerformed(evt);
            }
        });

        jLabel1.setText("Adresse IP");

        jButton1.setText("Envoyer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("( Ping, Masque Sous Reseau ..)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(AdresseIp, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButton2)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdresseIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        /**
         * Prend les informations entre chaque point
         */
        
        String[] ip = AdresseIp.getText().split("\\.");
        
        /**
         * Methode verifiant si AdresseIp contient bien 6 point et que elle ne dépasse pas la taille de 16 chiffres
         */
        
        if (ip.length != 4 || AdresseIp.getText().length() > 16) {
            JOptionPane.showMessageDialog(null, "Ce n'est pas une adresse IP");
            return;
        }

        

        Integer num = Integer.valueOf(ip[0]);
        
        if (num <= 127) {
            JOptionPane.showMessageDialog(null, "Classe A");
        } else if (num <= 172) {
            JOptionPane.showMessageDialog(null, "Classe B");
        } else if (num <= 192) {
            JOptionPane.showMessageDialog(null, "Classe C");
        } else {
            JOptionPane.showMessageDialog(null, "Classe D");
        }
        
//        JOptionPane.showMessageDialog(null, AdresseIp.getText());
        
//        String[] ip = AdresseIp.getText().split("\\.");
//        if (ip.length != 4) {
//            JOptionPane.showMessageDialog(null, "Ce n'est pas une adresse IP");
//            return;
//        }
//        for (int i = 0; i < ip.length; ++i) {
//            System.out.println(ip[i]);
//            Integer integer = Integer.getInteger(ip[i]);
//            if (integer == null) {
//                JOptionPane.showMessageDialog(null, "Entrée une ip");
//                return;
//            }
//        }
//        
//        for (int i = 0; i < ip.length; ++i) {
//            System.out.println(ip[i]);
//            if (ip[i].contains("")) {
//                Integer integer = Integer.getInteger(ip[i]);
//            }
//            Integer integer = Integer.getInteger(ip[i]);
//            if (integer == null) {
//                JOptionPane.showMessageDialog(null, "Ce n'est pas une adresse IP");
//                return;
//            }
//        }
// 
//
//
//        Integer num = Integer.valueOf(ip[0]);
//        if (num <= 127) {
//            JOptionPane.showMessageDialog(null, "Classe A");
//        } else if (num <= 172) {
//            JOptionPane.showMessageDialog(null, "Classe B");
//        } else if (num <= 192) {
//            JOptionPane.showMessageDialog(null, "Classe C");
//        } else {
//            JOptionPane.showMessageDialog(null, "Classe D");
//        }
//        
//        JOptionPane.showMessageDialog(null, AdresseIp.getText());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AdresseIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdresseIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdresseIpActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Sousreseau menu = new Sousreseau();      
        menu.setLocationRelativeTo(this);
        menu.setVisible(true);
        menu.run();
        throw new UnsupportedOperationException("Not supported yet.");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Saisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Saisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Saisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Saisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Saisie s = new Saisie();
                s.setLocationRelativeTo(null);
                s.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdresseIp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
